"use client";
import {useState} from "react";
import {ATTACKS} from "@/lib/asedio/demo";
import {runExperience} from "@/lib/experience/adapter";
import {useLocale} from "@/design-system/i18n/context";
import {useDemoRun} from "@/design-system/demo/use-demo-run";
import {TracePlayer} from "@/design-system/demo/trace-player";
import {traceCopy} from "@/lib/experience/trace-copy";
import {DecisionNarrative} from "@/lib/experience/story-visual";
import {AsedioScene} from "@/lib/experience/asedio-scene";
export default function Page(){const es=useLocale()==="es";const families=[...new Set(ATTACKS.map(a=>a.category))];const [target,setTarget]=useState<"vulnerable"|"hardened">("hardened"),[family,setFamily]=useState(families[0]),[scenario,setScenario]=useState("a"),demo=useDemoRun(runExperience),result=demo.run?.result;const reset=()=>{setTarget("hardened");setFamily(families[0]);setScenario("a");demo.reset()};const manual=(f:()=>void)=>{f();setScenario("");demo.reset()};const choose=(id:string)=>{setScenario(id);setFamily(families[0]);setTarget(id==="a"?"hardened":"vulnerable");demo.reset()};return <main className="min-h-screen bg-background px-6 py-16 text-foreground"><div className="mx-auto max-w-5xl"><DecisionNarrative kind="defense" locale={es?"es":"en"} selected={scenario} onScenario={choose}/><h1 className="text-4xl font-semibold">{es?"Observa la postura de defensa.":"Observe defense posture."}</h1><div className="mt-8 grid gap-6 md:grid-cols-2"><section className="min-w-0 rounded-xl border border-border p-5"><label>{es?"Objetivo":"Target"}<select className="mt-2 w-full rounded border bg-background p-2" value={target} onChange={e=>manual(()=>setTarget(e.target.value as "vulnerable"|"hardened"))}><option value="hardened">{es?"Endurecido":"Hardened"}</option><option value="vulnerable">{es?"Vulnerable":"Vulnerable"}</option></select></label><label className="mt-4 block">{es?"Familia":"Family"}<select className="mt-2 w-full rounded border bg-background p-2" value={family} onChange={e=>manual(()=>setFamily(e.target.value))}>{families.map(f=><option key={f}>{f}</option>)}</select></label><div className="mt-5 flex flex-wrap gap-2"><button className="min-w-0 flex-1 rounded bg-accent px-4 py-3 text-white" onClick={()=>demo.execute({target,families:[family]})}>{es?"Ejecutar":"Run checks"}</button><button className="rounded border px-3" onClick={demo.cancel}>{es?"Cancelar":"Cancel"}</button><button className="rounded border px-3" onClick={reset}>{es?"Reiniciar":"Reset"}</button></div>{demo.error&&<p className="mt-3 text-danger">{es?"No se pudo ejecutar la batería.":"The battery could not run."}</p>}</section><section className="min-w-0">{result&&demo.run?<TracePlayer translate={k=>traceCopy(es?"es":"en",k)} trace={demo.trace} locale={es?"es":"en"} executionMs={demo.run.executionMs} renderStage={frame=><AsedioScene frame={frame} input={demo.run!.input} result={result} locale={es?"es":"en"}/>}/>:<p>{es?"Elige una situación y ejecuta las pruebas.":"Choose a situation and run the tests."}</p>}</section></div></div></main>}